language: ruby
before_install:
  - gem install bundler --version 2.0.1
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'CREATE DATABASE myapp_test;'
rvm:
  - 2.5.1
env:
  - TESTCMD="bundle exec rspec -f d"
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec -f d
services:
 - mysql
